### ISSUE TITLE
Wiki documentation missing for 'Configuring Icecast outputs'

### ISSUE THREAD

**Issue by charlie-foxtrot** [szpajder/RTLSDR-Airband#153]
Icecast output supports a `send_scan_freq_tags` but not mentioned in the Wiki section

**Comment by szpajder** [comment]
https://github.com/szpajder/RTLSDR-Airband/wiki/Icecast-metadata-updates-in-scan-mode

**Comment by charlie-foxtrot** [comment]
same for this one, I missed it.  maybe add a link from https://github.com/szpajder/RTLSDR-Airband/wiki/Configuring-Icecast-outputs

the "Explanation of keywords" section missing one of the keywords threw me off

**Comment by szpajder** [comment]
If you missed it, then how did you know there is such a feature in the first place? :)

I avoid creating a full mesh of cross-links between pages in the Wiki because it disrupts the reading order and confuses beginners. There is a complete table of contents on the first page, which also shows up in the sidebar and that's enough.

**Comment by charlie-foxtrot** [comment]
> If you missed it, then how did you know there is such a feature in the first place? :)

noticed in the code then went back to the wiki looking for a description.

**Comment by szpajder** [comment]
As I said. I prefer to keep the main page of each topic short and simple, so that it does not act as a visual deterrent for newcomers. All the non-essential features have their respective pages in the "Advanced features" section.
