### ISSUE TITLE
Latency in streaming

### ISSUE THREAD

**Issue by on7qz** [szpajder/RTLSDR-Airband#21]
Hello,
I have managed to setup RTL_Airband(V2) on a Raspberry ( model 2 &3 ).
2 channels are monitored (spacing is 800 Khz) and streamed to an Icecast2 server running on the raspberry. Despite the fact that the CPU show less than 10 % usage on peak, I have noticed that the latency between the analog reception (with a hand scanner) and the output of the Icecast stream is about 15 to 30 sec. (depending from the buffer size).
 
Just wanted to know if this is normal or how can it be improved ? I know there will always be a difference but 1 sec is OK but 30 sec doesn't much sense ..
Thanks for advice

Yves

**Comment by szpajder** [comment]
Latency depends mainly on the buffer size in the client. Most clients' defaults work quite well for high-bitrate audio streams (music, etc). The first thing you should try is reducing the buffer size in your player. You can make it as small as you want, however, there is a tradeoff - with very short buffers, any network jitter or lost packet will immediately cause the buffer to get empty, which in turn wil cause gaps in audio, "Buffering..." messages, etc. 64 kbytes works OK for rtl_airband feeds, and it delays the audio less than 10 seconds.

Regarding server configuration, you have two options in icecast.xml, which affect latency:

- burst-on-connect - for low-speed audio it's best to set it to zero
- burst-size - default is 64k, it's good to reduce it to, eg. 12k

Regarding rtl_airband itself - it doesn't introduce any more delay than it's required to do MP3 compression. MPEG algorithm does not work in real time. It does spectrum analysis and runs a psychoacoustic model, both of which work on batches of audio data (typically a fraction of second long, at least). So it is necessary to collect some audio data first in order to be able to compress it. 

You may or may not be aware that all streams at liveatc.net or similar services are delayed at least 10+ seconds. Does it matter? Well, if you are listening to your local airport when standing at the fence and observing the events as they happen, it might matter, so the scanner would definitely be a better solution. But when you listen to a feed from an airport half a world away, is it really that important? I don't think so.
